name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install dependencies
      run: uv sync

    - name: Lint with ruff
      run: |
        uv run ruff check
        uv run ruff format --check

    - name: Install plugin
      run: uv pip install -e .

    - name: Test plugin functionality
      run: |
        cd test-site
        uv run mkdocs build
        # Verify core functionality
        test -f site/llms.txt
        test -f site/llms-full.txt  
        test -f site/index.md
        test -f site/quickstart/index.md
        # Check content has expected format
        grep -q "# Test Site" site/llms.txt
        grep -q "Quick Start Guide" site/quickstart/index.md